version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - @HOMEASSISTANT_DIR@/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      DISABLE_JEMALLOC: 'true'
##
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - @HOMEASSISTANT_DIR@/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - @HOMEASSISTANT_DIR@/nginx/ssl:/etc/nginx/ssl:ro
    network_mode: host
    restart: unless-stopped
##
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - /opt/matter-server:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - @HOMEASSISTANT_DIR@/mosquitto/config:/mosquitto/config
      - @HOMEASSISTANT_DIR@/mosquitto/data:/mosquitto/data
      - @HOMEASSISTANT_DIR@/mosquitto/log:/mosquitto/log

  whisper:
    container_name: Whisper
    image: rhasspy/wyoming-whisper
    network_mode: host
    runtime: nvidia
    volumes:
      - ./whisper:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Madrid
    command: --model small-int8 --language es
    restart: unless-stopped
##
  piper:
    container_name: Piper
    image: rhasspy/wyoming-piper
    network_mode: host
    runtime: nvidia
    volumes:
      - @HOMEASSISTANT_DIR@/piper:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Madrid
    command: --voice en-us-ryan-medium
    restart: unless-stopped
##
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    network_mode: host
    volumes:
      - @HOMEASSISTANT_DIR@/wakeword:/data
      - @HOMEASSISTANT_DIR@/wakeword:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Madrid
    command: --preload-model 'ok_nabu' --custom-model-dir /custom
    restart: unless-stopped
